#!/bin/env python

from os.path import abspath

env = Environment(CPPPATH = [abspath('../common')],
                  CPPFLAGS = ['-Wall', '-ggdb'])

opts = Options()

if env['PLATFORM'] == 'win32':
    opts.AddOptions(PathOption('prefix',
                               'Installation prefix',
                               'C:\\\\Syx', PathOption.PathAccept))
    env['bindir'] = env['datadir'] = env['rootdir'] = env['libdir'] = '$prefix'
    env['includedir'] = '$prefix\\\\include'
    env['docdir'] = '$prefix\\\\doc'
else:
    opts.AddOptions(
        PathOption('prefix',
                   'Installation prefix',
                   '/usr/local', PathOption.PathAccept),
        PathOption('datadir',
                   'Installation prefix for machine-independent data',
                   '$prefix/share', PathOption.PathAccept),
        PathOption('docdir',
                   'Installation prefix for documentation',
                   '$datadir/doc', PathOption.PathAccept),
        PathOption('libdir',
                   'Installation prefix for object code libraries',
                   '$exec_prefix/lib', PathOption.PathAccept),
        PathOption('includedir',
                   'Installation prefix for C header files',
                   '$prefix/include', PathOption.PathAccept))

opts.Update (env)
Help(opts.GenerateHelpText(env))

#=======================================================
#==== System Configuration
#=======================================================

conf = Configure(env)
#-------------------------------------------------------
print '\n' + 'Mandatory libraries...'
#-------------------------------------------------------
libraries = ['boost_serialization',
             'boost_system',
             'boost_thread']

for lib in libraries:
    if not conf.CheckLib(lib):
        print 'Did not find', lib, 'library'
        exit(1)

#-------------------------------------------------------
print '\n' + 'Mandatory headers...'
#-------------------------------------------------------
headers = ['boost/archive/text_iarchive.hpp',
           'boost/archive/text_oarchive.hpp',
           'boost/asio/buffer.hpp',
           'boost/asio/ip/tcp.hpp',
           'boost/asio/ip/udp.hpp',
           'boost/asio/placeholders.hpp',
           'boost/asio/read.hpp',
           'boost/asio/write.hpp',
           'boost/bind.hpp',
           'boost/lexical_cast.hpp',
           'boost/ref.hpp',
           'boost/scoped_ptr.hpp',
           'boost/thread/mutex.hpp',
           'boost/thread/once.hpp',
           'boost/thread/thread.hpp',
           'boost/tuple/tuple.hpp']

for header in headers:
    if not conf.CheckCXXHeader(header):
        print 'Did not find the', header, 'header.'
        exit(1)

print

env = conf.Finish()

Export('env', 'opts')
SConscript('./src/SConscript', build_dir='./build', duplicate=0)
