Import('env', 'opts')

sources = Split("""clientsMap.cpp
                   inputFactory.cpp
                   ioConnection.cpp
                   main.cpp
                   markerProcessor.cpp
                   receptionist.cpp
                   debugOutputs.cpp""")

env.Program('silver_server', sources)
