Import('env', 'install_nodes')

sources = Split("""clientsMap.cpp
                   inputFactory.cpp
                   ioConnection.cpp
                   main.cpp
                   markerProcessor.cpp
                   receptionist.cpp
                   debugOutputs.cpp""")

silver_server_node = env.Program('silver_server', sources)
silver_server = env.Alias('silver_server', silver_server_node)
Default(silver_server)

install_nodes.append(env.Install(env['bindir'], silver_server_node))
