/*
  File autogenerated by gengetopt version 2.19.1
  generated with the following command:
  gengetopt -i silvver_cameras.ggo 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "Controla a captura e processamento das imagens obtidas pelas câmeras";

const char *gengetopt_args_info_usage = "Usage: " CMDLINE_PARSER_PACKAGE " [OPTIONS]...";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "      --ip-servidor=IP          O endereço ip do silvver-servidor  \n                                  (default=`127.0.0.1')",
  "",
  "  -p, --porta-recepcionista=PORTA\n                                A porta onde o recepcionista do servidor está \n                                  ligado  (default=`12000')",
  "",
    0
};

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->ip_servidor_given = 0 ;
  args_info->porta_recepcionista_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->ip_servidor_arg = gengetopt_strdup ("127.0.0.1");
  args_info->ip_servidor_orig = NULL;
  args_info->porta_recepcionista_arg = 12000;
  args_info->porta_recepcionista_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{
  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->ip_servidor_help = gengetopt_args_info_help[2] ;
  args_info->porta_recepcionista_help = gengetopt_args_info_help[3] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  printf("\n%s\n\n", gengetopt_args_info_usage);

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n", gengetopt_args_info_description);

  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  
  if (args_info->ip_servidor_arg)
    {
      free (args_info->ip_servidor_arg); /* free previous argument */
      args_info->ip_servidor_arg = 0;
    }
  if (args_info->ip_servidor_orig)
    {
      free (args_info->ip_servidor_orig); /* free previous argument */
      args_info->ip_servidor_orig = 0;
    }
  if (args_info->porta_recepcionista_orig)
    {
      free (args_info->porta_recepcionista_orig); /* free previous argument */
      args_info->porta_recepcionista_orig = 0;
    }
  
  clear_given (args_info);
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  if (args_info->help_given) {
    fprintf(outfile, "%s\n", "help");
  }
  if (args_info->version_given) {
    fprintf(outfile, "%s\n", "version");
  }
  if (args_info->ip_servidor_given) {
    if (args_info->ip_servidor_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "ip-servidor", args_info->ip_servidor_orig);
    } else {
      fprintf(outfile, "%s\n", "ip-servidor");
    }
  }
  if (args_info->porta_recepcionista_given) {
    if (args_info->porta_recepcionista_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "porta-recepcionista", args_info->porta_recepcionista_orig);
    } else {
      fprintf(outfile, "%s\n", "porta-recepcionista");
    }
  }
  
  fclose (outfile);

  i = EXIT_SUCCESS;
  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}


/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;

  result = cmdline_parser_internal (argc, argv, args_info, override, initialize, check_required, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  return EXIT_SUCCESS;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "ip-servidor",	1, NULL, 0 },
        { "porta-recepcionista",	1, NULL, 'p' },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVp:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'p':	/* A porta onde o recepcionista do servidor está ligado.  */
          if (local_args_info.porta_recepcionista_given)
            {
              fprintf (stderr, "%s: `--porta-recepcionista' (`-p') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->porta_recepcionista_given && ! override)
            continue;
          local_args_info.porta_recepcionista_given = 1;
          args_info->porta_recepcionista_given = 1;
          args_info->porta_recepcionista_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->porta_recepcionista_orig)
            free (args_info->porta_recepcionista_orig); /* free previous string */
          args_info->porta_recepcionista_orig = gengetopt_strdup (optarg);
          break;


        case 0:	/* Long option with no short option */
          /* O endereço ip do silvver-servidor.  */
          if (strcmp (long_options[option_index].name, "ip-servidor") == 0)
          {
            if (local_args_info.ip_servidor_given)
              {
                fprintf (stderr, "%s: `--ip-servidor' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->ip_servidor_given && ! override)
              continue;
            local_args_info.ip_servidor_given = 1;
            args_info->ip_servidor_given = 1;
            if (args_info->ip_servidor_arg)
              free (args_info->ip_servidor_arg); /* free previous string */
            args_info->ip_servidor_arg = gengetopt_strdup (optarg);
            if (args_info->ip_servidor_orig)
              free (args_info->ip_servidor_orig); /* free previous string */
            args_info->ip_servidor_orig = gengetopt_strdup (optarg);
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
