Import('env', 'build_optional_flags', 'install_nodes')

if 'cleaning' in build_optional_flags:
    cleaning = True
else:
    cleaning = False

sources = Split("""cfParser.cpp
                   abstractCameras/abstractCamera.cpp
                   connection.cpp
                   sceneMounter.cpp
                   hardCameraFactory.cpp
                   main.cpp
                   abstractCameras/artkpCamera.cpp
                   abstractCameraFactory.cpp
                   hardCameras/hardCamera.cpp
                   hardCameras/pseudoCamera.cpp""")

if 'dc1394_control' in build_optional_flags or cleaning:
    sources += ['hardCameras/dc1394_1x.cpp',
                'hardCameras/conversions/bayer.c',
                'hardCameras/conversions/conversions.c']
elif 'dc1394' in build_optional_flags or cleaning:
    sources += ['hardCameras/dc1394_2x.cpp']

silvver_cameras_node = env.Program('silvver_cameras', sources)
Default(env.Alias('silvver_cameras', silvver_cameras_node))

install_nodes.append(env.Install(env['DESTDIR'] + env['bindir'],
                                 silvver_cameras_node))
