Import('env', 'opts', 'build_optional_flags')

if 'cleaning' in build_optional_flags:
    cleaning = True
else:
    cleaning = False

sources = Split("""cfParser.cpp
                   abstractCamera.cpp
                   homography.cpp
                   connection.cpp
                   sceneMounter.cpp
                   hardCamera.cpp
                   hardCameraFactory.cpp
                   main.cpp
                   markerCamera.cpp
                   markerExtractor.cpp
                   abstractCameraFactory.cpp
                   hardCameras/pseudoCamera.cpp
                   tsPrint.cpp""")

if 'dc1394_control' in build_optional_flags or cleaning:
    sources += ['hardCameras/dc1394_1x.cpp',
                'hardCameras/conversions.cpp']
elif 'dc1394' in build_optional_flags or cleaning:
    sources += ['hardCameras/dc1394_2x.cpp']

env.Program('silver_camera', sources)
