Import('env', 'build_optional_flags', 'install_nodes')

if 'cleaning' in build_optional_flags:
    cleaning = True
else:
    cleaning = False

sources = Split("""cfParser.cpp
                   abstractCamera.cpp
                   connection.cpp
                   sceneMounter.cpp
                   hardCamera.cpp
                   hardCameraFactory.cpp
                   main.cpp
                   artkpCamera.cpp
                   abstractCameraFactory.cpp
                   hardCameras/pseudoCamera.cpp""")

if 'dc1394_control' in build_optional_flags or cleaning:
    sources += ['hardCameras/dc1394_1x.cpp',
                'hardCameras/conversions/bayer.c',
                'hardCameras/conversions/conversions.c']
elif 'dc1394' in build_optional_flags or cleaning:
    sources += ['hardCameras/dc1394_2x.cpp']

silver_camera_node = env.Program('silver_camera', sources)
Default(env.Alias('silver_camera', silver_camera_node))

install_nodes.append(env.Install(env['bindir'], silver_camera_node))
