Import('env', 'opts')

sources = Split("""silvverDriver2_0.cpp""")

# sources = Split("""silvverDriver2_0.cpp""")

# sources  = Split("""epuckCamera.cpp
#                     epuckDriver2_0.cpp
#                     epuckInterface.cpp
#                     epuckIR.cpp
#                     epuckLEDs.cpp
#                     epuckPosition2d.cpp
#                     serialPort.cpp""")

# env.StaticLibrary('silvver_player', sources)
env.SharedLibrary('silvver_player', sources)
