Import('env', 'install_nodes')

sources = Split("""target.cpp
                   connection.cpp""")

static_client_node = env.StaticLibrary('silvver_client', sources)
shared_client_node = env.SharedLibrary('silvver_client', sources)

Default(env.Alias('sivver_client', [static_client_node, shared_client_node]))

install_nodes.append(env.Install(env['DESTDIR'] + env['libdir'],
                                 [static_client_node, shared_client_node]))
