Import('env', 'install_nodes')

sources = Split("""target.cpp
                   connection.cpp""")

static_client_node = env.StaticLibrary('silver_client', sources)
shared_client_node = env.SharedLibrary('silver_client', sources)

Default(env.Alias('siver_client', [static_client_node, shared_client_node]))

install_nodes.append(env.Install(env['libdir'],
                                 [static_client_node, shared_client_node]))
