Import('env', 'install_nodes')

sources = Split("""clientsMap.cpp
                   inputFactory.cpp
                   ioConnection.cpp
                   main.cpp
                   markerProcessor.cpp
                   receptionist.cpp
                   debugOutputs.cpp""")

silvver_server_node = env.Program('silvver_server', sources)
Default(env.Alias('silvver_server', silvver_server_node))

install_nodes.append(env.Install(GetOption('bindir'), silvver_server_node))
